SELECT COUNT(DISTINCT NAME) FROM ANIMAL_INS

# SELECT COUNT(NAME)
# FROM (SELECT *
#     FROM ANIMAL_INS
#     GROUP BY NAME ) AS NEW_ANIMAL_INS
    
# SELECT COUNT(NAME)
# FROM (SELECT DISTINCT NAME FROM ANIMAL_INS) AS NAME_LIST