-- 작성자: 김형준
-- SQL code style established by Gitlab

SELECT 
  CHILD.ID,
  (   
      SELECT 
        COUNT(*)
      FROM ECOLI_DATA PARENT
      WHERE CHILD.ID = PARENT.PARENT_ID
  ) CHILD_COUNT
FROM ECOLI_DATA CHILD
ORDER BY CHILD.ID

/*
SELECT 
  CHILD.ID, 
  COUNT(PARENT.ID) CHILD_COUNT
FROM ECOLI_DATA CHILD 
LEFT JOIN ECOLI_DATA PARENT
  ON CHILD.ID = PARENT.PARENT_ID
GROUP BY CHILD.ID
ORDER BY CHILD.ID
*/