SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O LEFT JOIN ANIMAL_INS I
ON O.ANIMAL_ID = I.ANIMAL_ID 
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID

# A > B, 어떤 B의 원소는 무조건 A에 있어야 하는데 없음, B에 있으면서 A에 없는 기록 찾기

# SELECT ANIMAL_ID, NAME
# FROM ANIMAL_OUTS
# WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS)
# ORDER BY ANIMAL_ID