-- 작성자: 김형준
-- SQL code style established by Gitlab

WITH CSHARP_OR_PYTHON_DEVELOPERS AS (
    SELECT 
      DISTINCT D.ID
    FROM DEVELOPERS D
    JOIN SKILLCODES S 
      ON D.SKILL_CODE & S.CODE = S.CODE
    WHERE S.NAME = 'C#' 
      OR S.NAME = 'Python'
)

SELECT 
  ID, 
  EMAIL, 
  FIRST_NAME, 
  LAST_NAME
FROM DEVELOPERS
WHERE ID IN 
    (SELECT ID FROM CSHARP_OR_PYTHON_DEVELOPERS)
ORDER BY ID;