SELECT CAR_TYPE, COUNT(CAR_TYPE) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%시트%'
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE ASC


# SELECT CAR_TYPE
#      ,  COUNT(car_id) AS CARS
# FROM CAR_RENTAL_COMPANY_CAR
# WHERE options REGEXP '통풍시트|열선시트|가죽시트'
# GROUP BY CAR_TYPE
# ORDER BY CAR_TYPE ASC